//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElCuernoVip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Detalles_Cuentas = new HashSet<Detalles_Cuentas>();
        }
    
        public int Id_Cuenta { get; set; }
        public Nullable<int> Mesa_Id { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
        public Nullable<int> Reservacion_Id { get; set; }
        public Nullable<int> Empleado_Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public bool Es_Reservacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Mesas Mesas { get; set; }
        public virtual Reservaciones Reservaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Cuentas> Detalles_Cuentas { get; set; }
    }
}
