//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElCuernoVip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Cuentas
    {
        public int Id_Detalle_Cuenta { get; set; }
        public Nullable<int> Venta_Id { get; set; }
        public Nullable<int> Producto_Id { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
