//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElCuernoVip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservaciones()
        {
            this.Cuentas = new HashSet<Cuentas>();
        }
    
        public int Id_Reservacion { get; set; }
        public Nullable<int> Mesa_Id { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
        public Nullable<System.DateTime> Fecha_Reservacion { get; set; }
        public Nullable<System.TimeSpan> Horario { get; set; }
        public Nullable<int> Num_Personas { get; set; }
        public string Estatus { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual Mesas Mesas { get; set; }
    }
}
